-- Tabela para registrar todas as transações de dopamina (créditos e débitos)

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  description TEXT NOT NULL,
  points INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('credit', 'debit')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) para a tabela
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Política para permitir que usuários leiam apenas suas próprias transações
CREATE POLICY "Allow users to read their own transactions" ON transactions
  FOR SELECT
  USING (auth.uid() = user_id);

-- Política para permitir que usuários insiram suas próprias transações
CREATE POLICY "Allow users to insert their own transactions" ON transactions
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);
